version: '3.8'

services:
  react-app:
    build: app/.
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nestjs:
    build: backend/.
    volumes:
      - ./backend/:/app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
