# Use an official Nginx image as the base
FROM nginx:alpine

# Copy the custom Nginx configuration file
COPY ./config.conf /etc/nginx/conf.d/default.conf 

# Copy the build files to the Nginx html directory
COPY app2/ /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]